# Generated by Django 2.2.7 on 2020-10-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inputrestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('restaurantname', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
    ]
